// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3kR_mmkdBETZ_kyQKp1mGpJz3MmSB8A8',
    appId: '1:457547624707:web:6320bff134c6c39fb4f936',
    messagingSenderId: '457547624707',
    projectId: 'my-flutter-0173',
    authDomain: 'my-flutter-0173.firebaseapp.com',
    storageBucket: 'my-flutter-0173.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf3TN8yKfQnoCeF9zLKN_v501r1wKZUHI',
    appId: '1:457547624707:android:ac1d32c5c3112bf1b4f936',
    messagingSenderId: '457547624707',
    projectId: 'my-flutter-0173',
    storageBucket: 'my-flutter-0173.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBznbCtJZQ6eDnfQeR-MR09wQ6F65KO7n4',
    appId: '1:457547624707:ios:2c5ab31f9d6c3b68b4f936',
    messagingSenderId: '457547624707',
    projectId: 'my-flutter-0173',
    storageBucket: 'my-flutter-0173.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBznbCtJZQ6eDnfQeR-MR09wQ6F65KO7n4',
    appId: '1:457547624707:ios:2c5ab31f9d6c3b68b4f936',
    messagingSenderId: '457547624707',
    projectId: 'my-flutter-0173',
    storageBucket: 'my-flutter-0173.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3kR_mmkdBETZ_kyQKp1mGpJz3MmSB8A8',
    appId: '1:457547624707:web:47f16002ccff390ab4f936',
    messagingSenderId: '457547624707',
    projectId: 'my-flutter-0173',
    authDomain: 'my-flutter-0173.firebaseapp.com',
    storageBucket: 'my-flutter-0173.firebasestorage.app',
  );
}
